CREATE TABLE prontuarios (
  id SERIAL PRIMARY KEY,
  patient_id INTEGER REFERENCES pacientes(id) UNIQUE,
  nome_completo VARCHAR(255),
  data_nascimento DATE,
  idade VARCHAR(10),
  sexo VARCHAR(20),
  profissao VARCHAR(100),
  telefone VARCHAR(20),
  endereco TEXT,
  antecedentes TEXT,
  medicamentos TEXT,
  cirurgias TEXT,
  queixa_principal TEXT,
  inicio_sintomas VARCHAR(255),
  fatores_agravantes TEXT,
  fatores_atenuantes TEXT,
  inspecao TEXT,
  palpacao TEXT,
  adm TEXT,
  forca_muscular TEXT,
  testes_especiais TEXT,
  diagnostico TEXT,
  objetivos_curto TEXT,
  objetivos_medio TEXT,
  objetivos_longo TEXT,
  condutas TEXT,
  tecnicas TEXT,
  exercicios TEXT,
  orientacoes TEXT,
  frequencia VARCHAR(100),
  assinatura VARCHAR(255),
  crefito VARCHAR(50)
);